/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static com.sun.java.accessibility.util.AWTEventMonitor.addWindowListener;
import dao.*;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author aluno
 */
public class FrmFornecedor extends javax.swing.JInternalFrame {

    MaskFormatter mfUf;
    MaskFormatter mfCep;
    MaskFormatter mfTel;
    MaskFormatter mfFax;
    MaskFormatter mfCnpj;
    MaskFormatter mfIe;
    MaskFormatter mfData;

    boolean gravar;
    boolean editar;

    int codigo;

    /**
     * Creates new form FrmCliente
     */
    public FrmFornecedor() {

        try {

            initComponents();

            mfUf = new MaskFormatter("UU");
            mfUf.setPlaceholderCharacter('_');
            mfUf.setValueContainsLiteralCharacters(false);
            mfUf.setValueClass(String.class);
            DefaultFormatterFactory dffUf = new DefaultFormatterFactory(mfUf);
            txtUf.setFormatterFactory(dffUf);

            mfCep = new MaskFormatter("#####-###");
            mfCep.setPlaceholderCharacter('_');
            mfCep.setValueContainsLiteralCharacters(false);
            mfCep.setValueClass(String.class);
            DefaultFormatterFactory dffCep = new DefaultFormatterFactory(mfCep);
            txtCep.setFormatterFactory(dffCep);

            mfTel = new MaskFormatter("(##)*####-####");
            mfTel.setPlaceholderCharacter('_');
            mfTel.setValidCharacters(" 123456789");
            mfTel.setValueContainsLiteralCharacters(false);
            mfTel.setValueClass(String.class);
            DefaultFormatterFactory dffTel = new DefaultFormatterFactory(mfTel);
            txtTelefone.setFormatterFactory(dffTel);

            mfFax = new MaskFormatter("(##)*####-####");
            mfFax.setPlaceholderCharacter('_');
            mfFax.setValidCharacters(" 123456789");
            mfFax.setValueContainsLiteralCharacters(false);
            mfFax.setValueClass(String.class);
            DefaultFormatterFactory dffFax = new DefaultFormatterFactory(mfFax);
            txtFax.setFormatterFactory(dffFax);

            mfCnpj = new MaskFormatter("##.###.###/####");
            mfCnpj.setPlaceholderCharacter('_');
            mfCnpj.setValidCharacters("123456789");
            mfCnpj.setValueContainsLiteralCharacters(false);
            mfCnpj.setValueClass(String.class);
            DefaultFormatterFactory dffCnpj = new DefaultFormatterFactory(mfCnpj);
            txtCnpj.setFormatterFactory(dffCnpj);

            mfIe = new MaskFormatter("###.###.###.###");
            mfIe.setPlaceholderCharacter('_');
            mfIe.setValidCharacters("123456789");
            mfIe.setValueContainsLiteralCharacters(false);
            mfIe.setValueClass(String.class);
            DefaultFormatterFactory dffIe = new DefaultFormatterFactory(mfIe);
            txtIe.setFormatterFactory(dffIe);

            mfData = new MaskFormatter("##/##/####");
            mfData.setPlaceholderCharacter('_');
            mfData.setValueContainsLiteralCharacters(true);
            mfData.setValueClass(String.class);
            DefaultFormatterFactory dffData = new DefaultFormatterFactory(mfData);
            txtDatacad.setFormatterFactory(dffData);

        } catch (Exception ex) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtRazao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFantasia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtFax = new javax.swing.JFormattedTextField();
        txtCnpj = new javax.swing.JFormattedTextField();
        txtIe = new javax.swing.JFormattedTextField();
        txtUf = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtDatacad = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFornecedores = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Fornecedor");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(null);
        setMaximumSize(new java.awt.Dimension(250, 250));
        setMinimumSize(new java.awt.Dimension(250, 250));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnGravar.setText("Gravar");
        btnGravar.setEnabled(false);
        btnGravar.setNextFocusableComponent(btnCancelar);
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.setNextFocusableComponent(txtRazao);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Razão");

        txtRazao.setEnabled(false);
        txtRazao.setNextFocusableComponent(txtFantasia);
        txtRazao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazaoActionPerformed(evt);
            }
        });

        jLabel3.setText("Endereço");

        txtEndereco.setEnabled(false);
        txtEndereco.setNextFocusableComponent(txtCidade);

        jLabel4.setText("Cidade");

        txtCidade.setEnabled(false);
        txtCidade.setNextFocusableComponent(txtBairro);

        jLabel5.setText("Bairro");

        txtBairro.setEnabled(false);
        txtBairro.setNextFocusableComponent(txtUf);

        jLabel10.setText("Nome Fantasia");

        txtFantasia.setEnabled(false);
        txtFantasia.setNextFocusableComponent(txtEndereco);

        jLabel11.setText("Fax");

        jLabel12.setText("CNPJ");

        jLabel13.setText("IE");

        txtFax.setEnabled(false);
        txtFax.setNextFocusableComponent(txtIe);

        txtCnpj.setEnabled(false);
        txtCnpj.setNextFocusableComponent(txtFax);

        txtIe.setEnabled(false);
        txtIe.setNextFocusableComponent(txtDatacad);

        txtUf.setEnabled(false);
        txtUf.setNextFocusableComponent(txtCep);

        jLabel6.setText("UF");

        jLabel7.setText("CEP");

        txtCep.setEnabled(false);
        txtCep.setNextFocusableComponent(txtTelefone);

        jLabel8.setText("Telefone");

        txtTelefone.setEnabled(false);
        txtTelefone.setNextFocusableComponent(txtCnpj);

        txtDatacad.setEnabled(false);

        jLabel9.setText("Data de Cadastro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCidade)
                                .addComponent(txtBairro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtUf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtIe, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtCnpj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDatacad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtRazao, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(417, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtDatacad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 28, Short.MAX_VALUE))
        );

        tblFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Razão", "Nome Fantasia", "Endereço", "Cidade", "Bairro", "UF", "CEP", "Telefone", "Fax", "CNPJ", "IE", "Data de Cadastro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblFornecedores);
        if (tblFornecedores.getColumnModel().getColumnCount() > 0) {
            tblFornecedores.getColumnModel().getColumn(0).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblFornecedores.getColumnModel().getColumn(1).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblFornecedores.getColumnModel().getColumn(2).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblFornecedores.getColumnModel().getColumn(3).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(3).setPreferredWidth(70);
            tblFornecedores.getColumnModel().getColumn(4).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(4).setPreferredWidth(50);
            tblFornecedores.getColumnModel().getColumn(5).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(5).setPreferredWidth(50);
            tblFornecedores.getColumnModel().getColumn(6).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(6).setPreferredWidth(30);
            tblFornecedores.getColumnModel().getColumn(7).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(7).setPreferredWidth(50);
            tblFornecedores.getColumnModel().getColumn(8).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(8).setPreferredWidth(50);
            tblFornecedores.getColumnModel().getColumn(9).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(9).setPreferredWidth(50);
            tblFornecedores.getColumnModel().getColumn(10).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(10).setPreferredWidth(50);
            tblFornecedores.getColumnModel().getColumn(11).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(11).setPreferredWidth(50);
            tblFornecedores.getColumnModel().getColumn(12).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(12).setPreferredWidth(50);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnIncluir)
                        .addGap(27, 27, 27)
                        .addComponent(btnAlterar)
                        .addGap(27, 27, 27)
                        .addComponent(btnExcluir)
                        .addGap(27, 27, 27)
                        .addComponent(btnPesquisar)
                        .addGap(27, 27, 27)
                        .addComponent(btnGravar)
                        .addGap(27, 27, 27)
                        .addComponent(btnCancelar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnPesquisar)
                    .addComponent(btnGravar)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        DaoFornecedor d = new DaoFornecedor();

        d.setRazao("");

        ArrayList<DaoFornecedor> ListaFornecedor;
        try {

            ListaFornecedor = d.pesquisar(d);
            AtualizaTable(ListaFornecedor);

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, "Ocorreu um erro no Banco "
                    + "de dados" + ex.getMessage(),
                    "Erro:", JOptionPane.ERROR_MESSAGE);

        } catch (ClassNotFoundException ex) {

            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao carregar "
                    + "o driver do BD" + ex.getMessage(),
                    "Erro:", JOptionPane.ERROR_MESSAGE);

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "Ocorreu um erro" + ex.getMessage(),
                    "Erro:", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_formWindowOpened

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        try {
            int codigo = Integer.parseInt(tblFornecedores.getValueAt(tblFornecedores.getSelectedRow(), 0).toString());

            Object[] opt = {" SIM ", " NÃO "};
            if (JOptionPane.showOptionDialog(this, "Deseja mesmo excluir esse cliente?", "Aviso",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                    opt, opt[1]) == JOptionPane.YES_OPTION) {

                DaoFornecedor dc = new DaoFornecedor();
                dc.setCodFor(codigo);
                dc.excluir();
                formWindowOpened(null);
            }

            System.out.println("Codigo: " + codigo);

        } catch (HeadlessException | ClassNotFoundException | NumberFormatException | SQLException ex) {

            JOptionPane.showMessageDialog(null, "Ocorreu um erro\n" + ex.getMessage(),
                    "Erro:", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        // TODO add your handling code here:

        HabilitarBotoes(false);
        HabilitarCampos(true);
        //txtCodFor.setEnabled(false);
        LimpaCampos();

        txtRazao.requestFocus();
        gravar = true;

    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        // TODO add your handling code here:

        try {

            DaoFornecedor dFor = new DaoFornecedor();

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

            dFor.setRazao(txtRazao.getText());
            dFor.setFantasia(txtFantasia.getText());
            dFor.setEndereco(txtEndereco.getText());
            dFor.setCidade(txtCidade.getText());
            dFor.setBairro(txtBairro.getText());
            dFor.setUf(txtUf.getText());
            dFor.setCep(txtCep.getValue().toString());
            dFor.setTelefone(txtTelefone.getValue().toString());
            dFor.setFax(txtFax.getValue().toString());
            dFor.setCnpj(txtCnpj.getValue().toString());
            dFor.setIe(txtIe.getValue().toString());
            dFor.setDatacad(sdf.parse(txtDatacad.getText()));

            if (gravar) {

                dFor.incluir();

            } else {

                //dFor.setCodFor(Integer.valueOf(txtCodFor.getText()));
                dFor.setCodFor(codigo);

                dFor.alterar();

            }

            HabilitarBotoes(true);
            HabilitarCampos(false);

            gravar = false;
            editar = false;
            LimpaCampos();

            formWindowOpened(null);

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, "Ocorreu um erro no Banco "
                    + "de dados" + ex.getMessage(),
                    "Erro1:", JOptionPane.ERROR_MESSAGE);

        } catch (ClassNotFoundException ex) {

            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao carregar "
                    + "o driver do BD" + ex.getMessage(),
                    "Erro2:", JOptionPane.ERROR_MESSAGE);

        } catch (ParseException ex) {

            JOptionPane.showMessageDialog(null, "Ocorreu um erro de conversão"
                    + ex.getMessage(),
                    "Erro3:", JOptionPane.ERROR_MESSAGE);

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "Ocorreu um erro"
                    + ex.getMessage(),
                    "Erro4:", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        HabilitarBotoes(false);
        HabilitarCampos(true);
        LimpaCampos();
        //txtCodFor.setEnabled(false);
        txtRazao.requestFocus();
        editar = true;
        try {

            if (tblFornecedores.getRowCount() > 0) {

                int posLinha = tblFornecedores.getSelectedRow();

                if (posLinha >= 0) {

                    //txtCodFor.setText(tblFornecedores.getValueAt(posLinha, 0).toString());
                    codigo = Integer.parseInt(tblFornecedores.getValueAt(posLinha, 0).toString());
                    txtRazao.setText(tblFornecedores.getValueAt(posLinha, 1).toString());
                    txtFantasia.setText(tblFornecedores.getValueAt(posLinha, 2).toString());
                    txtEndereco.setText(tblFornecedores.getValueAt(posLinha, 3).toString());
                    txtCidade.setText(tblFornecedores.getValueAt(posLinha, 4).toString());
                    txtBairro.setText(tblFornecedores.getValueAt(posLinha, 5).toString());
                    txtUf.setValue(tblFornecedores.getValueAt(posLinha, 6).toString());
                    txtCep.setValue(tblFornecedores.getValueAt(posLinha, 7).toString());

                    if (tblFornecedores.getValueAt(posLinha, 8).toString()
                            .equals("(__)_____-____")) {

                        txtTelefone.setValue("");

                    } else {

                        txtTelefone.setValue(
                                mfTel.stringToValue(tblFornecedores
                                        .getValueAt(posLinha, 8).toString()).toString());

                    }

                    txtFax.setValue(tblFornecedores.getValueAt(posLinha, 9).toString());
                    txtCnpj.setValue(tblFornecedores.getValueAt(posLinha, 10).toString());
                    txtIe.setValue(tblFornecedores.getValueAt(posLinha, 11).toString());
                    txtDatacad.setValue(tblFornecedores.getValueAt(posLinha, 12).toString());

                } else {

                    JOptionPane.showMessageDialog(null, "Selecione um cliente para alterar",
                            "Erro:", JOptionPane.ERROR_MESSAGE);
                    btnCancelarActionPerformed(null);

                }
            } else {

                JOptionPane.showMessageDialog(null, "Não existem clientes cadastrados!",
                        "Erro:", JOptionPane.ERROR_MESSAGE);
                btnCancelarActionPerformed(null);
            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "Ocorreu um erro" + ex.getMessage(),
                    "Erro:", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        DaoFornecedor c = new DaoFornecedor();

        String razao = JOptionPane.showInputDialog(null, "informe a razão social do fornecedor"
                + "ou parte dela: ", "Pesquisar", JOptionPane.QUESTION_MESSAGE);

        if (razao == null) {
            c.setRazao("");
            btnCancelar.setEnabled(false);
        } else {
            c.setRazao(razao);
            btnCancelar.setEnabled(true);
        }
        
        try {

            ArrayList<DaoFornecedor> ListaFornecedor = c.pesquisar(c);
            AtualizaTable(ListaFornecedor);

            

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, "Ocorreu um erro no Banco "
                    + "de dados" + ex.getMessage(),
                    "Erro:", JOptionPane.ERROR_MESSAGE);

        } catch (ClassNotFoundException ex) {

            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao carregar "
                    + "o driver do BD" + ex.getMessage(),
                    "Erro:", JOptionPane.ERROR_MESSAGE);

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "Ocorreu um erro" + ex.getMessage(),
                    "Erro:", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        HabilitarBotoes(true);
        HabilitarCampos(false);
        LimpaCampos();
        gravar = false;
        editar = false;
        formWindowOpened(null);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        formWindowOpened(null);
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtRazaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazaoActionPerformed

    private void LimpaTable() {

        DefaultTableModel model = (DefaultTableModel) tblFornecedores.getModel();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

    }

    private void AtualizaTable(ArrayList<DaoFornecedor> fornecedores) {

        LimpaTable();

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        if (!fornecedores.isEmpty()) {

            DefaultTableModel dadosFornecedores = (DefaultTableModel) tblFornecedores.getModel();

            String Linha[] = new String[]{"", "", "", "", "", "", "", "", ""};

            try {

                int pos = -1;

                for (DaoFornecedor fornecedor : fornecedores) {

                    pos++;

                    dadosFornecedores.addRow(Linha);

                    dadosFornecedores.setValueAt(fornecedor.getCodFor(), pos, 0);
                    dadosFornecedores.setValueAt(fornecedor.getRazao(), pos, 1);
                    dadosFornecedores.setValueAt(fornecedor.getFantasia(), pos, 2);
                    dadosFornecedores.setValueAt(fornecedor.getEndereco(), pos, 3);
                    dadosFornecedores.setValueAt(fornecedor.getCidade(), pos, 4);
                    dadosFornecedores.setValueAt(fornecedor.getBairro(), pos, 5);
                    dadosFornecedores.setValueAt(fornecedor.getUf().toUpperCase(), pos, 6);
                    dadosFornecedores.setValueAt(mfCep.valueToString(fornecedor.getCep()), pos, 7);
                    dadosFornecedores.setValueAt(mfTel.valueToString(fornecedor.getTelefone()), pos, 8);
                    dadosFornecedores.setValueAt(mfTel.valueToString(fornecedor.getFax()), pos, 9);
                    dadosFornecedores.setValueAt(mfCnpj.valueToString(fornecedor.getCnpj()), pos, 10);
                    dadosFornecedores.setValueAt(mfIe.valueToString(fornecedor.getIe()), pos, 11);
                    dadosFornecedores.setValueAt(sdf.format(fornecedor.getDatacad()), pos, 12);

                }

                tblFornecedores.setModel(dadosFornecedores);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro no Banco "
                        + "de dados" + ex.getMessage(),
                        "Erro:", JOptionPane.ERROR_MESSAGE);
            }

        }

    }

    private void HabilitarBotoes(boolean hab) {

        btnIncluir.setEnabled(hab);
        btnAlterar.setEnabled(hab);
        btnExcluir.setEnabled(hab);
        btnPesquisar.setEnabled(hab);
        btnGravar.setEnabled(!hab);
        btnCancelar.setEnabled(!hab);

    }

    private void HabilitarCampos(boolean hab) {

        //txtCodFor.setEnabled(hab);
        txtRazao.setEnabled(hab);
        txtFantasia.setEnabled(hab);
        txtEndereco.setEnabled(hab);
        txtCidade.setEnabled(hab);
        txtBairro.setEnabled(hab);
        txtUf.setEnabled(hab);
        txtCep.setEnabled(hab);
        txtTelefone.setEnabled(hab);
        txtFax.setEnabled(hab);
        txtCnpj.setEnabled(hab);
        txtIe.setEnabled(hab);
        txtDatacad.setEnabled(hab);

    }

    private void LimpaCampos() {

        //txtCodFor.setText("");
        txtBairro.setText("");
        txtCep.setText("");
        txtCidade.setText("");
        txtDatacad.setText("");
        txtEndereco.setText("");
        txtRazao.setText("");
        txtFantasia.setText("");
        txtTelefone.setText("");
        txtFax.setText("");
        txtCnpj.setText("");
        txtIe.setText("");
        txtUf.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblFornecedores;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JFormattedTextField txtCnpj;
    private javax.swing.JFormattedTextField txtDatacad;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtFantasia;
    private javax.swing.JFormattedTextField txtFax;
    private javax.swing.JFormattedTextField txtIe;
    private javax.swing.JTextField txtRazao;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JFormattedTextField txtUf;
    // End of variables declaration//GEN-END:variables
}
